feat(WEB-17): DropdownInput 공통 컴포넌트 제작
uoslife/client-meeting-season4 pull request #16
Opened 2024-02-21 14:02 UTC by alicehrk

### DropdownInput 컴포넌트 제작

## 개요
- DropdownInput 공통 컴포넌트를 제작하였습니다.
<img width="380" alt="image" src="https://github.com/uoslife/client-meeting-season4/assets/81912837/b225ca6d-6fb5-49b2-a9ac-2d9c236a6f9b">

## 상세설명
Dropdown 컴포넌트에서 사용하는 props에 대해 설명하면 다음과 같습니다.
- label: 해당 컴포넌트를 사용하는 주제 (ex) 나이 선택, 키 선택
- value: 현재 선택된 값
- setValue: 사용자가 새로운 값을 선택했을 때, 그 선택을 반영하는 함수
- options: Dropdown에서 사용자가 선택할 수 있는 옵션 (ex) 20, 21, 22, ...

2024-02-21 15:37 UTC, eunbae0 requested changes

2024-02-21 15:37 UTC, eunbae0 commented on src/components/inputs/dropdownInput/DropdownInput.tsx
> +                <S.DropdownOption onClick={onClickOptionSelect(val)} key={i}>
배열의 index를 key로 사용하는 것은 지양하는게 좋습니다.
-[관련문서](https://medium.com/sjk5766/react-%EB%B0%B0%EC%97%B4%EC%9D%98-index%EB%A5%BC-key%EB%A1%9C-%EC%93%B0%EB%A9%B4-%EC%95%88%EB%90%98%EB%8A%94-%EC%9D%B4%EC%9C%A0-3ce48b3a18fb)

2024-02-21 15:37 UTC, eunbae0 commented on src/components/inputs/dropdownInput/DropdownInput.tsx
모든 태그를 div로 구현해도 동작하는데 상관은 없지만, 웹 표준을 지켜서 [input과 options태그](https://www.w3schools.com/html/html_form_elements.asp)를 적절히 사용하는 방식으로 변경하면 좋을 것 같습니다.

2024-02-21 15:37 UTC, eunbae0 commented on src/components/inputs/dropdownInput/DropdownInput.tsx
> +    <div>
props의 타입을 'button'으로 확장했지만, 해당 컴포넌트에서 'button' props을 사용하지 못하기에 아래와 같이 props를 구조분해할당으로 넘겨줘야 온전히 타입이 확장된 컴포넌트로 사용할 수 있습니다.
```ts
const DropdownInput = ({
  value,
  setValue,
  label,
  options,
  ...props,
}: DropdownInputProps) => {
// ...

  return (
    <div {...props}>
```

추가적으로 DropdownInput 컴포넌트는 div 태그로 감싸고 있기 때문에 'div'로 변경해야하며, 확장 element로 'button'은 적절하지 않아 보입니다.

input과 options 태그로 해당 컴포넌트를 구현한다면 'input'으로 변경하면 됩니다.

2024-02-22 04:10 UTC, ratafa commented on src/components/inputs/dropdownInput/DropdownInput.tsx
시멘틱 태그에 대해 알아봅시다~

2024-02-22 04:19 UTC, ratafa reviewed
고생 많으셨습니다~ 은배님이 리뷰를 잘 해주셔서 제가 리뷰할게 크게 없네요~

2024-02-22 04:19 UTC, ratafa commented on src/components/inputs/dropdownInput/DropdownInput.style.tsx
> +    ${props =>
${({showOption}) => showOption ? `${colors.Primary500}` : `${colors.Gray300}`};
이런 식으로 객체 문법을 사용해서 축약이 가능합니다~

2024-02-23 06:46 UTC, limeojin363 approved these changes

2024-02-23 06:46 UTC, limeojin363 commented on src/components/inputs/dropdownInput/DropdownInput.style.tsx
> +  ${() => typographies.GoThicButtonM};
요거 '() =>' 생략해도 잘 작동합니다

2024-02-23 13:34 UTC, limeojin363 requested changes

2024-02-23 13:34 UTC, limeojin363 commented on src/components/inputs/dropdownInput/DropdownInput.tsx
> +    value: string | number;
string | number 타입이 많이 쓰이는 것 같은데
`type ValueType = string | number`로 값의 타입을 미리 정의해주고 사용하면 어떨까요?

2024-02-23 13:34 UTC, limeojin363 commented on src/components/inputs/dropdownInput/DropdownInput.tsx
> +                : value
string type에도 .toString()이 사용 가능하므로 `? value.toString()`으로 대체해도 괜찮을 것 같습니다. 삼항연산자 중첩이 가독성을 떨어뜨려서 개인적으로는 이쪽이 나아 보이네요.

2024-02-26 15:30 UTC, merged