feat(WEB-26): ParticipationModal 컴포넌트 제작
uoslife/client-meeting-season4 pull request #17
Opened 2024-02-22 19:47 UTC by soeun2537

### ParticipationModal 컴포넌트 제작

## 구현

- ParticipationModal 컴포넌트를 제작했습니다.
<img width="400" src="https://github.com/uoslife/client-meeting-season4/assets/83596813/81f08bba-0fe7-48a6-a17f-9021493b2780">
<br/>

## 컴포넌트 속성 설명
**ParticipationModal 컴포넌트 속성 설명**
- isActive: true로 업데이트 되면 modal이 뜸
- label: 팅 이름
- currentParticipant: 현재 참여자 수 표시
- maxParticipant: 최대 참여자 수 표시 (1 or 3)
- cancelButtonClicked: 취소 버튼 클릭
- joinButtonClicked: 참여 버튼 클릭
<br/>

## 이후 추가 예정
- 글씨체 오류 수정
- 인원수 표시 부분 글씨체 수정
<br/>

## 테스트 코드
```
import ParticipationModal from './components/modal/participationModal/ParticipationModal';

function App() {
  return (
    <>
      <ParticipationModal
        isActive={true}
        label={'시립대의 등대조형관'}
        currentParticipant={1}
        maxParticipant={3}
        cancelButtonClicked={() => {}}
        joinButtonClicked={() => {}}
      />
    </>
  );
}

export default App;
```

2024-02-23 13:14 UTC, limeojin363 requested changes

2024-02-23 13:14 UTC, limeojin363 commented on src/components/modal/participationModal/ParticipationModal.tsx
> +  maxParticipant: 1 | 3;
`maxParticipant`가 1인 경우는 아래 케이스를 위한 것인가요? 해당 모달에서 이 경우까지 처리할 생각이신지 아니면 다른 모달을 작성해서 처리할 생각이신지 궁금합니다.

![image](https://github.com/uoslife/client-meeting-season4/assets/97388599/e6908981-91a0-423f-b893-19f9ddf3d0aa)

2024-02-23 13:14 UTC, limeojin363 commented on src/components/modal/participationModal/ParticipationModal.tsx
> +  joinButtonClicked: () => void;
`~clicked`는 형용사로 오해할 여지가 있어서 `~ButtonHandler`나 `~Handler` 쪽이 좀 더 알아보기 쉬운 변수명인 것 같습니다!

2024-02-25 09:43 UTC, ratafa approved these changes
react에서는 createPortal이라는 방식을 통해 모달을 편하게 만들 수 있습니다.
물론 지금의 방식 역시 틀린 방법은 절대로 아닙니다.
나중에 모달을 직접 구현하셔야한다면 createPortal 방식을 사용하시는 것을 적극 권장 드립니다.
https://heeeming.tistory.com/entry/React-React-Portal-%EA%B8%B0%EC%88%A0%EC%9D%84-%EC%9D%B4%EC%9A%A9%ED%95%98%EC%97%AC-Modal%EC%9D%84-%EB%A7%8C%EB%93%9C%EB%8A%94-%EB%B0%A9%EB%B2%95%EC%8B%A4%EC%8A%B5%ED%8C%8C%EC%9D%BC-%ED%95%98%EB%8B%A8-%EC%B2%A8%EB%B6%80

2024-02-28 03:56 UTC, merged