feat: Input 공통 컴포넌트 제작
uoslife/client-meeting-season4 pull request #2
Opened 2024-02-04 06:52 UTC by soeun2537

### Input 컴포넌트 제작

## 개요

- Input 공통 컴포넌트를 제작했습니다.

  <img src="https://github.com/uoslife/client-meeting-season4/assets/83596813/8cf0621c-bb4f-48de-bc50-f49fc4d1ead0" width="400">
  <img src="https://github.com/uoslife/client-meeting-season4/assets/83596813/687c91de-9f2d-49ec-8113-aa3fc494c296" width="310" >

## 상세설명
**Input 컴포넌트 속성 설명**

- status: default(기본), focused(input 클릭 시), filled(값이 있을 시), error(오류 생겼을 시)
- placeholder: input 칸 기본으로 있는 문구 (ex: "text", "웹메일 주소 입력" 등)
- onClick: 외부 훅 사용하여 컴포넌트 관리
- isAuthentication: 인증번호 버튼 On/Off에 따라 X icon 표시

**이후 추가 예정**

- 글씨체
- icon (현재 dummy 컴포넌트)

2024-02-04 10:07 UTC, ratafa reviewed
고생 많으셨습니다~ 😃

2024-02-04 10:07 UTC, ratafa commented on src/compents/inputs/Input.tsx
> +        <S.Icon isAuthentication={isAuthentication}></S.Icon>
1. x 버튼의 유무는 내부에서 처리하는게 좋아보여요! 
- isAuthentication은 clear 버튼, 즉 X 버튼의 유무를 판단할 수 있는 목적의 boolean 값으로 판단됩니다. 하지만 외부에서 isAuthentication 로직을 처리할 수 있게 해두셨어요. 그것보다는 Input 컴포넌트 내부적으로 처리할 수 있게 하는게 더 좋아보입니다!
<예시 코드>
<img width="417" alt="image" src="https://github.com/uoslife/client-meeting-season4/assets/89263598/b7056054-7020-4754-b78e-5e56d8f52ccb">

2. 버튼을 눌렀을 때, value 값을 초기화 시켜주는 함수가 필요해 보입니다! 변수명은 onClearValue의 느낌이면 괜찮을 것 같습니다.

2024-02-04 10:07 UTC, ratafa commented on src/compents/inputs/Input.tsx
> +  value?: string;
1. 필수적으로 필요하다 생각되는 값은 Optional Propery로 처리하지 않는게 좋아보여요!
- value와 같이 반드시 필요한 값은 value :  string 처리하는게 좋아보여요!

2024-02-07 04:08 UTC, alicehrk approved these changes

2024-02-07 04:08 UTC, alicehrk commented on src/compents/inputs/Input.style.tsx
> +      return '#F47F88';
error 색상도 HEX대신, 정의되어 있는 상수 `${colors.Red200}`로 통일시켜도 좋을 것 같아요😀

2024-02-07 16:11 UTC, limeojin363 requested changes
첫 PR이네요 수고 많으셨습니다 ㅎㅎ

2024-02-07 16:11 UTC, limeojin363 commented on src/hooks/useInputHook.tsx
> +  };
두 함수로 나눠 처리하신 이유가 있을까요?

```ts
  const handleInput = (e: ChangeEvent<HTMLInputElement>) => {
    setInputValue(e.target.value);
  };
```

이렇게 작성하여도 로직상 큰 문제는 없어보이는데, 혹시나 달리 이유(의도)가 있다면 알려주세요!

2024-02-07 16:11 UTC, limeojin363 commented on src/hooks/useInputHook.tsx
> +  };
`setValueClear` 쪽이 조금 더 깔끔한 작명이라고 생각됩니다.

2024-02-07 16:24 UTC, soeun2537 commented on src/hooks/useInputHook.tsx
> +  };
![image](https://github.com/uoslife/client-meeting-season4/assets/83596813/35373c22-e923-424b-84f6-b7c3321fbba9)
figma에서 email 주소를 작성하는 input이 있는데, 각 학교에서 메일로 인증하는거면 어차피 메일 @ 뒷부분은 정해져있을 것 같아서요! 저 input @ 뒷부분은 각 학교의 메일로 설정해두고 앞부분만 수정하게끔 하려고 하는데 어떻게 구현을 해야할지 모르겠어서 핸들링하다가 안 합친 것 같네요..!

2024-02-09 07:32 UTC, merged