feat[WEB-31]: 공통 "대학 이메일 인증" 페이지 제작
uoslife/client-meeting-season4 pull request #22
Opened 2024-02-27 10:55 UTC by ratafa

# 공통 "대학 이메일 인증" 페이지 제작

## 개요
- 레이아웃 사용시 사이드 이펙트로 인해, Col 레이아웃 컴포넌트의 height와 fill props을 제거했습니다.
- TextInput 컴포넌트의 children 속성을 추가했습니다.
- 공통 "대학 이메일 인증" 페이지를 제작했습니다.

## 상세설명
**공통 "대학 이메일 인증" 페이지를 보자면...**
<img width="478" alt="image" src="https://github.com/uoslife/client-meeting-season4/assets/89263598/3bbcdc41-5034-4910-88bc-72784d9eef61">

## 잔여작업
- 인증 값 입력 Input과 인증하기 Button status에 따른 상태변화 switch 문 추가
- 이메일 인증 api 부착

2024-02-28 14:55 UTC, alicehrk requested changes

2024-02-28 14:55 UTC, alicehrk commented on src/pages/common/univVerificationStep/SecondPage.tsx
> +  const { validateCodeValue, setValidateCodeCleaer, handleValidateCodeValue } =
`setValidateCoderClear` 오타난 것 같습니당!

2024-02-28 14:55 UTC, alicehrk commented on src/pages/common/univVerificationStep/SecondPage.tsx
> +  const handleValidate = () => {};
tryValidate와 그냥 validate의 차이는 무엇인가요??

2024-02-29 13:39 UTC, ratafa commented on src/pages/common/univVerificationStep/SecondPage.tsx
> +  const { validateCodeValue, setValidateCodeCleaer, handleValidateCodeValue } =
그러네요! 감사합니다! ㅎㅎㅎ

2024-02-29 13:41 UTC, ratafa commented on src/pages/common/univVerificationStep/SecondPage.tsx
> +  const handleValidate = () => {};
아 제가 기차에서 작성하느라 이런 디테일을 챙기지 못했네요 handleValidate와 handleTryValidate는 같은 기능을 담당하는 함수입니다!

대학 이메일 인증 페이지의 경우, api가 있어야지 제대로 제작이 가능할 것 같아서 일단 대강 형태만 잡아놨습니다!

좋은 피드백 감사드립니다!

2024-03-03 10:49 UTC, limeojin363 approved these changes
![image](https://github.com/uoslife/client-meeting-season4/assets/97388599/32868e66-bacc-4e9d-8ac4-0eb2d2f380be)

useInput도 미완성이고 API도 안나왔고 아직 리뷰할건 특별히 없네요.
하람님말씀대로 변수명만 손보시고 merge하면 될듯합니다~

2024-03-04 14:42 UTC, merged