feat(WEB-15): Icon 컴포넌트 작성
uoslife/client-meeting-season4 pull request #5
Opened 2024-02-08 10:07 UTC by ratafa

### Icon 컴포넌트 제작

## 개요
- Icon 공통 컴포넌트를 제작했습니다.
- icon type을 만들었습니다.

## 상세설명
**Icon 컴포넌트를 받는 props에서 기본적으로 필요한 것들에 대해 설명하자면...**
-  iconName: 사용할 아이콘의 이름을 받습니다.(아이콘 이름은 public/images/icon/${iconName}이 기준입니다.)
   width: 아이콘의 폭을 지정해줍니다.
   height: 아이콘의 높이를 지정해줍니다.
   rotate: Footer처럼 아이콘의 방향만 달리 해야할 경우, 방향을 조절할 수 있습니다.
   onClick: 아이콘 클릭 시, 함수를 넣어줍니다.
![image](https://github.com/uoslife/client-meeting-season4/assets/89263598/f654463d-f715-4644-bab9-68fd45eb555f)

만약 public/images/icon/animals에서 아이콘을 사용한다면?
![image](https://github.com/uoslife/client-meeting-season4/assets/89263598/b4e1f7f9-75c9-4bb4-acea-1f1b5d58f678)

_**단, 반드시 배열 데이터에 animalKeyType[]처럼 타입을 지정해서 넣어주셔야 합니다!**_ 
만약 배열 데이터에 타입을 따로 지정해주지 않으면 에러가 터집니다. 이유는 TypeScript가 배열 ANIMALS에 대한 구체적인 타입 정보를 알지 못하기 때문입니다. ANIMALS 배열이 'dog', 'cat', 'rabbit'의 문자열만을 포함하고 있지만, TypeScript는 이를 일반적인 string 배열로 추론합니다. 따라서 이 배열의 각 요소를 템플릿 리터럴에 사용하면 결과는 'animals/${string}'이 되고, 이는 iconType에 할당할 수 없기 때문에 오류가 발생합니다.

그렇기에, animalKeyType를 icon.type에서 import 해서 animalKeyType에 [] 배열로 만든다고 붙이기만 하면 됩니다!

2024-02-09 02:09 UTC, limeojin363 requested changes

2024-02-09 07:27 UTC, ratafa commented on src/components/buttons/iconButton/IconButton.tsx
> +    <S.Wrapper type="button" onClick={onClick} rotate={rotate} {...props}>
오 좋은 제안인 것 같아요 vamos

2024-02-09 07:31 UTC, ratafa commented on src/components/buttons/roundButton/RoundButton.tsx
>  export type Props = Combine<
컨벤션으로 통일하면 좋을 것 같아요~

2024-02-09 09:42 UTC, alicehrk approved these changes

2024-02-09 09:42 UTC, alicehrk commented on src/components/buttons/iconButton/IconButton.style.tsx
> +import styled from '@emotion/styled';
그 import 순서 지정하는 규칙은 따로 없는거죠?? 자유롭게 작성하면 될까용??

2024-02-09 09:42 UTC, alicehrk commented on src/components/buttons/iconButton/IconButton.style.tsx
> +  cursor: pointer;
모바일 환경에서도 `cursor: pointer;`가 필요한가요? 어떤 효과를 위한 것인지 궁금합니다!

2024-02-10 07:43 UTC, ratafa commented on src/components/buttons/iconButton/IconButton.style.tsx
> +  cursor: pointer;
외대와 경희대에서 웹 접근이 가능하다고 들었어요~
진짜 만약에 컴퓨터로 오는 흑우같은 친구들을 위해서 대응했답니다...

2024-02-10 07:44 UTC, ratafa commented on src/components/buttons/iconButton/IconButton.style.tsx
> +import styled from '@emotion/styled';
넵 자유입니다~

2024-02-10 07:44 UTC, merged